apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Values.name .Values.namespace}}
  labels:
    app: {{ printf "%s-%s" .Values.name .Values.namespace}}
    app.kubernetes.io/name: {{ printf "%s-%s" .Values.name .Values.namespace}}
    app.kubernetes.io/component: {{ printf "%s-%s" .Values.name .Values.namespace}}
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{ printf "%s-%s" .Values.name .Values.namespace}}
      app.kubernetes.io/name: {{ printf "%s-%s" .Values.name .Values.namespace}}
      app.kubernetes.io/component: {{ printf "%s-%s" .Values.name .Values.namespace}}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Values.name .Values.namespace}}
        app.kubernetes.io/name: {{ printf "%s-%s" .Values.name .Values.namespace}}
        app.kubernetes.io/component: {{ printf "%s-%s" .Values.name .Values.namespace}}
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - name: {{ printf "%s-%s" .Values.name .Values.namespace}}
        image: {{.Values.image}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{.Values.cpu}}
            memory: {{.Values.memory}}
        ports:
        - containerPort: {{.Values.servicePort}}
          name: http-{{.Values.name}}
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /robots.txt
            port: {{.Values.servicePort}}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: {{.Values.servicePort}}
          timeoutSeconds: 1
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: {{.Values.name}}-pv
          - name: grafana-config
            mountPath: /etc/grafana/grafana.ini
            subPath: grafana.ini
          - name: grafana-dashboard-providers
            mountPath: /etc/grafana/provisioning/dashboards/dashboardproviders.yaml
            subPath: dashboardproviders.yaml
          - name: dashboards-k8s-cluster-summary
            mountPath: /var/lib/grafana/dashboards/k8s-cluster-summary

          - name: dashboards-node-exporter-full
            mountPath: /var/lib/grafana/dashboards/node-exporter-full

      volumes:
        - name: {{.Values.name}}-pv
          persistentVolumeClaim:
            claimName: {{.Values.name}}-pvc
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-dashboard-providers
          configMap:
            name: grafana-dashboard-providers
        - name: dashboards-k8s-cluster-summary
          configMap:
            name: grafana-dashboards-k8s-cluster-summary

        - name: dashboards-node-exporter-full
          configMap:
            name: grafana-dashboards-node-exporter-full

        
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.name}}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi